### ISSUE TITLE
v2.0.0-7 - SSR window undefined

### ISSUE THREAD

**Issue by djeeg** [gilbarbara/react-joyride#329]
Here: https://github.com/gilbarbara/react-joyride/blob/V2/src/styles.js#L28-L33

This lets nodejs compile
```
if (typeof window !== 'undefined' && window.innerWidth > 480) {
  width = 380;
} else if (typeof window !== 'undefined' && window.innerWidth > 768) {
  width = 490;
}
```
Still working on integrating v2, there may be other references that need to be tweaked ...

**Comment by gilbarbara** [comment]
v2 still is not ready for SSR and probably will break in other parts.

**Comment by gilbarbara** [comment]
It's probably better to skip Joyride to render anything while being served by SSR. This would prevent all other errors

**Comment by gilbarbara** [comment]
@djeeg sweet!
I'll just fix the keyboard navigation and I'll add SSR support for 2.0.0-8

**Comment by gilbarbara** [comment]
fixed

**Comment by djeeg** [comment]
Trying 2.0.0-8, it failes to compile in nodejs

With this

```
import Joyride from "react-joyride";
import {ACTIONS, EVENTS, LIFECYCLE, STATUS} from "react-joyride/lib/constants";
```

Throws compile error

```
process.on.uncaughtException ReferenceError: window is not defined
    at Object.<anonymous> (node_modules\react-joyride\lib\index.js:725:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
```


This commit does prevent rendering on server
https://github.com/gilbarbara/react-joyride/commit/113a753bebd9a6dd8bef2b4ccb3b8eb45690984f

However styles.js is still executed on server as its included by this module chain
- https://github.com/gilbarbara/react-joyride/blob/V2/src/modules/step.js#L7
- https://github.com/gilbarbara/react-joyride/blob/V2/src/components/index.js#L17
- https://github.com/gilbarbara/react-joyride/blob/V2/src/index.js#L1 

My current workaround is to conditionally import (its a bit messy though)

```
var Joyride = null;
var JoyrideConstants = null;
var ACTIONS = null;
var EVENTS = null;
var LIFECYCLE = null;
var STATUS = null;
if (process.env.IS_CLIENT) {
    Joyride = require("react-joyride").default;
    JoyrideConstants = require("react-joyride/lib/constants");
    ACTIONS = JoyrideConstants.ACTIONS;
    EVENTS = JoyrideConstants.EVENTS;
    LIFECYCLE = JoyrideConstants.LIFECYCLE;
    STATUS = JoyrideConstants.STATUS;
} else {
    //doesnt node compile
}
```

**Comment by djeeg** [comment]
Hmm maybe the title of this issue could be tweaked, not really wanting react-joyride to render on the server (aka SSR), its wanting the component import to be safe for universal rendering.

The error happens on node process startup, before any node reques, there is a reference to `window ` in the the global module import chain (outside of the component class instances)

Some other examples of libraries that have had a similar problem
- https://github.com/webpack/react-starter/issues/37#issuecomment-93943419
- https://github.com/reactjs/react-chartjs/issues/57#issuecomment-271106746

A simple check typeof `window !== 'undefined'` in styles.js is all thats needed to make react-joyride compatible with universal rendering (admittedly with no content being rendered)

In react-modal, it looks like they also protect a global call to window with EE.canUseDOM

```
import ExecutionEnvironment from "exenv";
const EE = ExecutionEnvironment;
const SafeHTMLElement = EE.canUseDOM ? window.HTMLElement : {};
```

https://github.com/reactjs/react-modal/blob/master/src/helpers/safeHTMLElement.js#L5

**Comment by gilbarbara** [comment]
yeah, I was getting the `window.innerWidth` outside styles function declaration and this could break compilation.
It will be in 2.0.0-9 soon.

Thanks

**Comment by shreysaroch** [comment]
Is it fixed now?
I'm on 2.0.0-10 and getting this: 

`Users/shreysaroch/Documents/work/xseed-assessment/node_modules/react-joyride/es/constants.js:51
export default index;
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shreysaroch/Documents/work/xseed-assessment/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/shreysaroch/Documents/work/xseed-assessment/src/common/components/views/LandingPage/components/DemoPage.jsx:9:1)
    at Module._compile (module.js:635:30)
    at loader (/Users/shreysaroch/Documents/work/xseed-assessment/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/shreysaroch/Documents/work/xseed-assessment/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
`

**Comment by gilbarbara** [comment]
@shreysaroch This is not related to the issue.
Your setup is probably excluding node_modules from babel transpiling.
Try loading it with `lib/constants` instead.

**Comment by jazzdragon** [comment]
@gilbarbara I have a pretty straight forward setup (create-react-app, jest), and got the same error as @shreysaroch. This solution you wrote here is great, but was a bit hard to find. It might be worth it to include it in the docs somehow.
