### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'nodeName')

### ISSUE THREAD

**Issue by RuchirB** [gilbarbara/react-joyride#969]
Not sure what causes this. it always happens when I click a specific button in my react app.

```
The above error occurred in the <ReactFloater> component:

    at ReactFloater (http://localhost:3000/static/js/bundle.js:85292:5)
    at div
    at JoyrideStep (http://localhost:3000/static/js/bundle.js:110038:5)
    at div
    at Joyride (http://localhost:3000/static/js/bundle.js:110301:5)
    at div
    at DashboardV2 (http://localhost:3000/static/js/bundle.js:3029:5)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:92648:5)
    at Routes (http://localhost:3000/static/js/bundle.js:93138:5)
    at Router (http://localhost:3000/static/js/bundle.js:93076:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:91265:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

**Comment by gilbarbara** [comment]
Hey @RuchirB 

I need a codesandbox with a minimal reproducible example.
