### ISSUE TITLE
isRequiredIf is not a function from "react-floater"

### ISSUE THREAD

**Issue by ramadhanabs** [gilbarbara/react-joyride#974]
Hello, when i try to build my app on docker image, it shows error message like this

`> Build error occurred
#12 97.12 TypeError: isRequiredIf is not a function
#12 97.12     at Object.<anonymous> (/usr/app/node_modules/react-floater/lib/index.js:211:7832)
#12 97.12     at Module._compile (internal/modules/cjs/loader.js:1063:30)
#12 97.12     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
#12 97.12     at Module.load (internal/modules/cjs/loader.js:928:32)
#12 97.12     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
#12 97.12     at Function.wrappedLoad [as _load] (/usr/app/node_modules/newrelic/lib/shimmer.js:313:24)
#12 97.12     at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
#12 97.12     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
#12 97.12     at async Loader.import (internal/modules/esm/loader.js:166:24) {
#12 97.12   type: 'TypeError'
#12 97.12 }`

Seems like it comes from 'react-floater' dependencies, any help?

**Comment by juniorforlife** [comment]
I'm having the same issue. It was fine a couple days ago.

**Comment by shubham-chavda** [comment]
Facing same issue.

**Comment by ucheol2** [comment]
Same issue

**Comment by juniorforlife** [comment]
@gilbarbara please take a look since this is a critical issue

**Comment by philippenunes** [comment]
Same issue

**Comment by gilbarbara** [comment]
I'll fix it today

**Comment by juniorforlife** [comment]
I think the issue is react-joyride depends on react-floater which depends on popperjs but they did some breaking changes so it messed up joyride. I forked your joyride repo to update floater version to 0.9.2 instead of 0.7.6 and was able to build successfully. However my Joyride component stops working

**Comment by Adelao4** [comment]
(internal/modules/esm/module_job.js:152:23) #12 97.12 at async
Loader.import (internal/modules/esm/loader.js:166:24) { #12 97.12 type:
'TypeError' #12 97.12 }

**Comment by gilbarbara** [comment]
Fixed in 2.7.1
